title = "My New Hugo Site"
languageCode = "en-us"
theme = "hugo-creative-portfolio-theme"
baseurl = "https://primeroz.github.io/przvape/"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "Products"
  url = "products/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

